theme: jekyll-theme-slate

github:
  is_project_page: false

title: "Join us for a beach walk, on Sunday September 6th at 9:45 AM at Goodman's Bay Park, in protest over the beach closures in The Bahamas"
description: ""
